addSbtPlugin("edu.gemini"            % "sbt-lucuma-app"      % "0.6.2")
addSbtPlugin("io.spray"              % "sbt-revolver"        % "0.9.1")
addSbtPlugin("com.typesafe.sbt"      % "sbt-site"            % "1.4.1")
addSbtPlugin("com.typesafe.sbt"      % "sbt-ghpages"         % "0.6.3")
addSbtPlugin("com.github.sbt"        % "sbt-native-packager" % "1.9.7")
